* np.array()
* np.arange()
* np.random.randint()
* np.in1d()
* np.intersect1d()
* Boolean Indexing
* np.where

# __SCALAR VALUE__

In [1]:
import numpy as np

a : np.ndarray = np.array(1000)
print(type(a))
print(a.dtype)
print(a.size)
print(a.shape)
print(a.itemsize)
print(a.ndim)

<class 'numpy.ndarray'>
int32
1
()
4
0


# __VECTOR VALUE__

In [2]:
import numpy as np
a : np.ndarray = np.array([1,2,3])
print(type(a))
print(a.dtype)
print(a.size)
print(a.shape)
print(a.itemsize)
print(a.ndim)

<class 'numpy.ndarray'>
int32
3
(3,)
4
1


# __MATRIX__

In [4]:
import numpy as np
a : np.ndarray = np.array([[1,2,3],[3,4,5]])
print(type(a))
print(a.dtype)
print(a.size)
print(a.shape)
print(a.itemsize)
print(a.ndim)

<class 'numpy.ndarray'>
int32
6
(2, 3)
4
2


# _Numpy With NDArray Typing Support_

In [9]:
!pip install nptyping beartype

   ---------------------------------------- 0.0/872.4 kB ? eta -:--:--
   ---- ----------------------------------- 92.2/872.4 kB 5.1 MB/s eta 0:00:01
   ------ --------------------------------- 143.4/872.4 kB 1.7 MB/s eta 0:00:01
   -------- ------------------------------- 194.6/872.4 kB 1.2 MB/s eta 0:00:01
   ---------- ----------------------------- 225.3/872.4 kB 1.1 MB/s eta 0:00:01
   ---------- ----------------------------- 235.5/872.4 kB 1.0 MB/s eta 0:00:01
   ------------ ------------------------- 286.7/872.4 kB 930.9 kB/s eta 0:00:01
   -------------- ----------------------- 337.9/872.4 kB 952.6 kB/s eta 0:00:01
   ---------------- --------------------- 368.6/872.4 kB 916.6 kB/s eta 0:00:01
   ----------------- -------------------- 409.6/872.4 kB 911.8 kB/s eta 0:00:01
   -------------------- ----------------- 460.8/872.4 kB 929.0 kB/s eta 0:00:01
   ----------------------- -------------- 532.5/872.4 kB 902.0 kB/s eta 0:00:01
   ------------------------ ------------- 563.2/87

In [11]:
from nptyping import NDArray,Shape,UInt64

data : NDArray[Shape["10"],UInt64] = np.arange(10)
data 


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
from nptyping import NDArray,Shape,UInt64

data : NDArray[Shape["10"],UInt64] = np.arange(1,50,2)
data 


array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [15]:
from nptyping import NDArray,Shape
from typing import Any

data : NDArray[Shape["10"],Any] = np.arange(1,50,2)
data + 10 

array([11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43,
       45, 47, 49, 51, 53, 55, 57, 59])

# To see time for execution

In [16]:
%%time
from nptyping import NDArray,Shape
from typing import Any

data : NDArray[Shape["10"],Any] = np.arange(1,50,2)
data + 10 

CPU times: total: 0 ns
Wall time: 0 ns


array([11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43,
       45, 47, 49, 51, 53, 55, 57, 59])

## _NUMPY ADVANCED OPERATIONS VS LIST OPERATIONS_ 

# __LIST__

In [18]:
data : list[int] = list(range(1,21))
print(data)
print(data[5:11])
data[5] = 1000
print(data)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
[6, 7, 8, 9, 10, 11]
[1, 2, 3, 4, 5, 1000, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]


In [19]:
data : list[int] = list(range(1,21))
print(data)
print(data[5:11])
data[5:11] = 1000
print(data)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
[6, 7, 8, 9, 10, 11]


TypeError: can only assign an iterable

# __NUMPY__

In [21]:
ndata : NDArray[Shape["20"],Any] = np.arange(1,21)
print(ndata)
print(ndata[5:11])
ndata[5:11] = 1000
print(ndata)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 6  7  8  9 10 11]
[   1    2    3    4    5 1000 1000 1000 1000 1000 1000   12   13   14
   15   16   17   18   19   20]


## __NUMPY 1D FUNCTIONS__

In [38]:
state_bank : NDArray[Shape["10"],Any] = np.array([1,7,8,10])
ubl_bank : NDArray[Shape["100"],Any] = np.random.randint(1,100,20) #1 se 100 k drmian 20 number generate kr do
print(state_bank)
print(ubl_bank)

[ 1  7  8 10]
[60 90  3 31 87 89 49 81 71  8 52  4 29 75 25 21 32 69 73 83]


In [39]:
np.in1d(state_bank,ubl_bank) # np.in1d(konse elements dhondhwane hain,kahan se dhundhwane hn)

array([False, False,  True, False])

# __INTERSECTION__

In [40]:
np.intersect1d(state_bank,ubl_bank)

array([8])

# __BOOLEAN INDEXING__

In [30]:
from nptyping import Bool
state_bank : NDArray[Shape["10"],Any] = np.array([1,7,8,10])
select : NDArray[Shape['10'],Bool] = np.array([True,False,False,True])

state_bank[select]

array([ 1, 10])

In [31]:
state_bank : NDArray[Shape["10"],Any] = np.array([1,7,8,10])
state_bank[state_bank % 2 == 0]

array([ 8, 10])

# __where__

In [41]:
x : NDArray[Shape["10"],Any] = np.array([1,7,8,10])
y : NDArray[Shape["10"],Any] = np.array([12,13,14,15])
np.where(x > y,x,y)

array([12, 13, 14, 15])

### __CREATE NUMPY ARRAYS__

In [43]:
a : NDArray[Shape["Size,Size"],Any] = np.array([[1,2,3],
                                                   [4,5,6]])

b : NDArray[Shape["*,*"],Any] = np.array([[1,2,3],
                                                   [4,5,6]])

c : NDArray[Shape["Size,Size"],Any] = np.array([["A"],
                                                   ["B"]])

In [44]:
np.who()

Name            Shape            Bytes            Type

_               4                16               int32
__              1                4                int32
___             4                4                bool
a               2 x 3            24               int32
_11             10               40               int32
_12             25               100              int32
_13             25               100              int32
_14             25               100              int32
_15             25               100              int32
_16             25               100              int32
ndata           20               80               int32
state_bank      4                16               int32
ubl_bank        20               80               int32
select          4                4                bool
_24             2                8                int32
_25             2                8                int32
_27             2                8                

# Create any dimension array

In [52]:
a : NDArray[Shape["Size"],Any] = np.arange(3*3).reshape(3,3)
b : NDArray[Shape["Size,Size"],Any] = np.arange(5*3).reshape(5,3)
print(a)
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [53]:
a : NDArray[Shape["Size,Size,Size"],Any] = np.arange(5*3*3).reshape(5,3,3)
b : NDArray[Shape["Size,Size,Size"],Any] = np.arange(5*2*2).reshape(5,2,2)
print(a)
print(b)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]

 [[27 28 29]
  [30 31 32]
  [33 34 35]]

 [[36 37 38]
  [39 40 41]
  [42 43 44]]]
[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]

 [[12 13]
  [14 15]]

 [[16 17]
  [18 19]]]


In [57]:
a : NDArray[Shape["Size,Size,Size"],Any] = np.arange(5*3*3).reshape(5,3,3)
print(a[::,::,::])

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]

 [[27 28 29]
  [30 31 32]
  [33 34 35]]

 [[36 37 38]
  [39 40 41]
  [42 43 44]]]


In [56]:
a : NDArray[Shape["Size,Size,Size"],Any] = np.arange(5*3*3).reshape(5,3,3)
print(a[::2,::,::])

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]

 [[36 37 38]
  [39 40 41]
  [42 43 44]]]


In [58]:
a : NDArray[Shape["Size,Size,Size"],Any] = np.arange(5*3*3).reshape(5,3,3)
print(a[::,::2,::])

[[[ 0  1  2]
  [ 6  7  8]]

 [[ 9 10 11]
  [15 16 17]]

 [[18 19 20]
  [24 25 26]]

 [[27 28 29]
  [33 34 35]]

 [[36 37 38]
  [42 43 44]]]


In [59]:
a : NDArray[Shape["Size,Size,Size"],Any] = np.arange(5*3*3).reshape(5,3,3)
print(a[::,::,::2])

[[[ 0  2]
  [ 3  5]
  [ 6  8]]

 [[ 9 11]
  [12 14]
  [15 17]]

 [[18 20]
  [21 23]
  [24 26]]

 [[27 29]
  [30 32]
  [33 35]]

 [[36 38]
  [39 41]
  [42 44]]]


In [60]:
a : NDArray[Shape["Size,Size,Size"],Any] = np.arange(5*3*3).reshape(5,3,3)
print(a[a % 2 == 0])

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44]


In [61]:
np.asarray([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [62]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [63]:
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [68]:
np.ones(3)

array([1., 1., 1.])

In [67]:
np.ones([2,2])

array([[1., 1.],
       [1., 1.]])

In [71]:
np.ones_like(a) #a ka skeleton hoga but value 1 hogy

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [73]:
a : NDArray[Shape["Size,Size,Size"],Any] = np.arange(5*3*3).reshape(5,3,3)
a[0:-1,::,::]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]],

       [[27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

In [74]:
a : NDArray[Shape["Size,Size,Size"],Any] = np.arange(5*3*3).reshape(5,3,3)
a[[0,-1],::,::]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[36, 37, 38],
        [39, 40, 41],
        [42, 43, 44]]])

In [77]:
state_bank : NDArray[Shape["10"],Any] = np.array([1,7,8,10])
print(state_bank.min())
print(state_bank.max())
print(state_bank.max())
print(state_bank.argmax())
print(state_bank.argmin())

1
10
10
3
0
